### ISSUE TITLE
Configurable profile page for user

### ISSUE THREAD

**Issue by jaakkom** [p2-inc/phasetwo-admin-portal#107]
Would be nice to have configurable view of profile edit page. So user would edit his specific attributes from ui.

What do you think? Examples:

- Phone number in attributes
- some other info about user

**Comment by xgp** [comment]
Yes. We have it as an enhancement to build the profile page from the `UserProfileMetadata` that comes from the declarative user profile configuration. 

Duplicate of [#81](https://github.com/p2-inc/phasetwo-admin-portal/issues/81)
