### ISSUE TITLE
Invitation email from admin portal has no link to accept invitation

### ISSUE THREAD

**Issue by SangI762** [p2-inc/phasetwo-admin-portal#108]
Hello, I've been testing the invitation flow and as the organization owner, I send an invitation from the admin portal.
But the receiver got an email without a link to accept:

`EMAIL has been invited to join SecondCompany at Realm by NAME (email). To accept or reject this invitation, click on the link below to log in.`
 
What am I missing?

**Comment by xgp** [comment]
You can either customize the email template in the organization extension
- https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/resources/theme-resources/templates/text/invitation-email.ftl
- https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/resources/theme-resources/templates/html/invitation-email.ftl

or set the `redirectUrl` when making the call to the endpoint https://phasetwo.io/api/add-organization-invitation. There is currently no default link, as there wouldn't be a way to know which `client_id` to use.

**Comment by SangI762** [comment]
@xgp Hmm, okay, but when I register with the invited email (using admin-portal client) I do not become a member of the organization. Should I add something to the link, query parameter, or something? 
So, I don't know how it works, even if I add a static link to the email template.

**Comment by xgp** [comment]
Also, if you don't want to update the code/themes to add a link to the invitation emails, you can do it in the admin UI in *Styles*->*Emails*
![image](https://github.com/p2-inc/phasetwo-admin-portal/assets/244253/cd0dd301-df84-4359-b984-ea768b6ef87a)
