### ISSUE TITLE
Portal Theme Fetches Default Icons from incorrect realm path

### ISSUE THREAD

**Issue by ThomasAunvik** [p2-inc/phasetwo-admin-portal#109]
![image](https://github.com/p2-inc/phasetwo-admin-portal/assets/9968151/e6de258f-ceb4-4696-8154-8d61237a8af0)
![image](https://github.com/p2-inc/phasetwo-admin-portal/assets/9968151/85ea96b0-50aa-43a1-ad98-07c3ad56a47a)

**Comment by xgp** [comment]
@pnzrr This should be realmId rather than realmName.
