### ISSUE TITLE
Portal doesn't open when missing / on realm/portal

### ISSUE THREAD

**Issue by ThomasAunvik** [p2-inc/phasetwo-admin-portal#110]
Misses a redirect.
Painstakenly thought that the portal was fully broken with no without thinking that it could have been an url missing a /.

![image](https://github.com/p2-inc/phasetwo-admin-portal/assets/9968151/9cb02719-db61-438e-b76e-5ba7de88c412)
![image](https://github.com/p2-inc/phasetwo-admin-portal/assets/9968151/bfc01f97-8f0a-44f6-b8e8-ec55d5dfbe8e)

**Comment by xgp** [comment]
@ThomasAunvik Thanks for reporting. 

@pnzrr This is loading the HTML and JS but not rendering when there's no trailing `/` or further path.
