### ISSUE TITLE
Update README with new colors and realm attribute keys

### ISSUE THREAD

**Issue by xgp** [p2-inc/phasetwo-admin-portal#117]
Now that we added the 100-900 colors, we need to update the README file with new colors, screenshot of the admin, and realm attribute keys.
https://github.com/p2-inc/phasetwo-admin-portal/blob/main/README.md

**Comment by pnzrr** [comment]
Already updated
https://github.com/p2-inc/phasetwo-admin-portal?tab=readme-ov-file#style
