### ISSUE TITLE
[Question] Localization & Translation

### ISSUE THREAD

**Issue by GME-O** [p2-inc/phasetwo-admin-portal#121]
Hi 

I have a question regarding Admin Portal translation. 
Is it possible to setup multiple language / translations and let the user change language like in Keycloak with the login theme ? (or automatically switch based on user's localization attributes).

I see that on admin portal you can specify a localization, but the UI is not translated. Is it possible to configure or customize that ?

Thanks in advance
Best regards,

**Comment by xgp** [comment]
Theoretically the infrastructure is there for it

All the messages live in https://github.com/p2-inc/phasetwo-admin-portal/tree/main/public/locales/

and it gets setup here https://github.com/p2-inc/phasetwo-admin-portal/blob/main/src/i18n.ts

but we've never had anyone use anything but English.

I'd suggest trying adding another language, and then PR if it requires changes to get it working.

**Comment by GME-O** [comment]
Thanks for your quick answer!

That's because you don't know french customer 😄 even a wrong translation is reported to us. 

As I'm using https://github.com/p2-inc/phasetwo-containers for exploration & testing, I guess it would require to get both, add translation in admin-portal and re-build a custom image with the updated admin portal (including translation) ? 

Thanks again

**Comment by xgp** [comment]
Yes, you'd have to rebuild this and then override the `phasetwo-admin-portal` jar in the `/opt/keycloak/providers/` dir and rebuild.

**Comment by pnzrr** [comment]
@GME-O we now have a French translation. Going to close the issue

https://github.com/p2-inc/phasetwo-admin-portal/pull/123

**Comment by MGLL** [comment]
@pnzrr I know :) (it was my other account). 
Have a good day

**Comment by pnzrr** [comment]
Ha ok, i wondered but wasn't sure
