### ISSUE TITLE
mvn clean build error

### ISSUE THREAD

**Issue by bensaadmohamed** [p2-inc/phasetwo-admin-portal#141]
hello
when i build the extension with mvn clean packege to generate a jar file it give an error 
./login/index.html doesnt exist

**Comment by xgp** [comment]
Sorry, there not enough here for me to reproduce. **When** does it give that error? **How** are you installing and running it?

**Comment by bensaadmohamed** [comment]
Ok, I'll try to clarify things a little
I think the problem is with the packagege json variable PUBLIC_URL when building on windows
the %PUBLIC_URL% variable  in Index.html file has no value .  so the CSS and JS has not been loaded correctly 
I replaced "PUBLIC_URL= '${authUrl}/realms/${realmName}/portal' react-scripts" in package.json
with  "Set PUBLIC_URL= ${authUrl}/realms/${realmName}/portal&&react-scripts build",
After building this time the variable %PUBLIC_URL% got replaced by <base href="http://localhost:8080/reams/ ??/portal/" /> but 
The variable ${realmName} has no value and has not been replaced

**Comment by xgp** [comment]
Sorry but I have no ability to debug on Windows. If you want to figure out the problem and submit a patch that will work on all platforms, happy to look at it. In the meantime, I recommend you build on a unix variant.
