### ISSUE TITLE
Clarify how to get back out of the Identify Provider Wizard

### ISSUE THREAD

**Issue by justintilson** [p2-inc/phasetwo-admin-portal#145]
After setting up a connection to my Google Workspace account, I am unable to navigate back to the dashboard using the available menu options.

![idp-no-escape](https://github.com/p2-inc/phasetwo-admin-portal/assets/1480031/99df3f08-0edc-4753-9866-3b388034edf2)

**Comment by xgp** [comment]
@justintilson did it open in a separate window? The assumption was that you would just close out when you were done. If it didn't then it might be a bug.

**Comment by justintilson** [comment]
Ah, you are right. I didn't notice my first time through. It's not really a bug then, just a source usability friction for new users.

**Comment by xgp** [comment]
I think we could probably be more clear about that, and even keep a link/info in the dropdown that says "go back from where I came from".

**Comment by pnzrr** [comment]
wrong repo for issue, addressed in `idp-wizard`
