### ISSUE TITLE
No button to add a password after logging in with a Google Workspace account

### ISSUE THREAD

**Issue by justintilson** [p2-inc/phasetwo-admin-portal#147]
<img width="976" alt="Screenshot 2024-05-01 at 10 39 56 AM" src="https://github.com/p2-inc/phasetwo-admin-portal/assets/1480031/b0feb5a3-67ae-4f9a-b975-a3f897abdff8">

I'd expect some functionality here to configure a password or a message saying that this is disabled because login is delegated to Google for my account.

**Comment by justintilson** [comment]
I see how this works now. I was able to login using my email add the temporary login link. No password required.

Is the password section only for those who signed up with an email and password?

I'm still left the feeling that functionality is missing / incomplete in the password section.

**Comment by pnzrr** [comment]
We'll add some copy for that. Thanks for calling it out.
