### ISSUE TITLE
Localizations for spanish are missing in Portal

### ISSUE THREAD

**Issue by vgallegob** [p2-inc/phasetwo-admin-portal#154]
Hello, 

I managed to enable different languages in Login app.

But the Portal doesen't seem to have been translated. Is that correct?

![image](https://github.com/p2-inc/phasetwo-admin-portal/assets/122233066/fcbf0f2b-f7a8-4d98-889d-226acb5f5edb)

**Comment by xgp** [comment]
Correct. The only 3 languages are currently English, French and Korean. You can find the translations here: https://github.com/p2-inc/phasetwo-admin-portal/tree/main/public/locales

Please feel free to PR if you want to add Spanish.

**Comment by vgallegob** [comment]
Will look into it

Enviado desde Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Garth ***@***.***>
Enviado: Thursday, July 4, 2024 11:13:04 PM
Para: p2-inc/phasetwo-admin-portal ***@***.***>
Cc: Víctor Gallego Betorz ***@***.***>; Author ***@***.***>
Asunto: Re: [p2-inc/phasetwo-admin-portal] Localizations for spanish are missing in Portal (Issue #154)


Correct. The only 3 languages are currently English, French and Korean. You can find the translations here: https://github.com/p2-inc/phasetwo-admin-portal/tree/main/public/locales

Please feel free to PR if you want to add Spanish.
