### ISSUE TITLE
Allow users with specific roles to create Organization on Admin Portal theme

### ISSUE THREAD

**Issue by klevinism** [p2-inc/phasetwo-admin-portal#158]
Hi, we are currently using keycloak for our authentication layer and would like to add organizations extension. 
Our use case requires that specific administrators should be allowed to be able to create new organizations. We are not able to figure out if there is an option to add organizations from the admin portal. Is there such an implementation?
Thank you!

**Comment by xgp** [comment]
No. If the user has the `create-organization` permission, they can add new organizations, but you would need to create your own UI for that in your application

**Comment by klevinism** [comment]
Thanks for your fast response!
