### ISSUE TITLE
Reopen issue 87 - wrong url of css and scripts when opening portal

### ISSUE THREAD

**Issue by cedric-beurtheret-jcd** [p2-inc/phasetwo-admin-portal#89]
#87 is not solved, so I want to reopen it.

**Comment by johnsvanda** [comment]
@xgp When this will be added to the main docker image  quay.io/phasetwo/phasetwo-keycloak please?  

@cedric-beurtheret-jcd Also If I want to build the jar on my own, am I supposed to specify somewhere the authUrl? 

Thank you so much.

**Comment by cedric-beurtheret-jcd** [comment]
@johnsvanda No, to build the jar, you just need to fetch the repo and launch mvn clean package.

The authUrl is needed if you want to test the portal as a standalone app. Then you should pass the url of your keycloak instance.

**Comment by xgp** [comment]
@johnsvanda we'll do a release later this week. We usually bundle a few features/bugfixes before releasing an image.
