### ISSUE TITLE
Setup SSO button goes to non-existent page

### ISSUE THREAD

**Issue by gboor** [p2-inc/phasetwo-admin-portal#93]
Playing around with this with the Docker image that contains all the plugins. After setting up an organisation and assigning a user, I can log in to the admin portal as that user and it seems to mostly work. However, when I click the "setup SSO" button, it takes me to a Keycloak 404 page with this URL;

http://localhost:8080/auth/realms/master/wizard/?org_id=[whatever]

It seems that /wizard/ does not work for any parameters. Is this broken, or am I missing some additional setup steps here?

**Comment by gboor** [comment]
Nevermind; just found in the docs this is not included in the open source portion.

**Comment by xgp** [comment]
Thanks for the question @gboor . This is (currently) only available as a licensed extension or using the hosted version at https://phasetwo.io

**Comment by SangI762** [comment]
@xgp Any chances that this will be available for open source as well?

**Comment by xgp** [comment]
@SangI762 we have it on the roadmap to open source a portion that includes the generic OIDC and SAML wizards. However, the vendor wizards consume significant resources to maintain, and drive a lot of our revenue, so we are unlikely to open source all of it.
