### ISSUE TITLE
Feature: Enable/Disable Members

### ISSUE THREAD

**Issue by juliusstoerrle** [p2-inc/phasetwo-admin-portal#97]
It would be great if users can be enabled or disabled from the "Members" table.

I would propose the addition of a button with the relevant caption to the actions menu and an indicator for disabled users in the table. E.g. strikethrough the name and/or add a disabled caption next to it or as a next to the roles.

Would that be in your interest? Happy to try a PR

**Comment by xgp** [comment]
There is not currently a “disabled” state for organization membership. Do you mean if the User object for that member is disabled?

**Comment by juliusstoerrle** [comment]
> There is not currently a “disabled” state for organization membership. Do you mean if the User object for that member is disabled?

Yes, I was referring to the existing property on the normal KC user object.

**Comment by xgp** [comment]
Got it. I think it’s reasonable to show disabled state. Please PR if you have time. Thank you!

**Comment by juliusstoerrle** [comment]
I created PR #98 for the indicator. I tried to follow styles I have seen in the app before, not sure if you have other preferences.
 
I would also like to see a button to change the state in the MemberActionMenu. However, none of the endpoints currently included in the client supports it. The KC AccountRestService does not have the property included nor any of your Org endpoints. I guess the options are to try the normal KC User endpoint or modify a P2 Orgs endpoint. What would you suggest @xgp?
If going for the KC User endpoint, how would you prefer it to be included - by modifying the Profile OpenApi Gist or by creating a new CodeGen Schema for the user endpoint?

**Comment by pnzrr** [comment]
Merged
